answer1 = 'олимпийка'
answer2 = 'драфтинг'
answer3 = 'лежак'
answer4 = ['финишер', 'финишёр']
answer5 = 'ТРАНЗИТКА'
answer6 = 'Бутусов'
answer7 = 'Бессемеровский'
answer8 = 'Н'
answer9 = ['19', 'XIX']
answer10 = '113'
answer11= 'Р'
answer12= 'спринт'
answer13= ['избранных', 'избранные']
answer14= 'кольцо'
answer15= ''
answer16= ''